### ISSUE TITLE
The onScroll event can not be fired

### ISSUE THREAD

**Issue by fanzihui** [swenyang/react-iscroll#1]
I am using the onScroll event can not be triggered, so the specific Y-axis distance or drop-down can not be calculated

**Comment by swenyang** [comment]
Did you pass `iscroll-probe.js` to `iScroll` props? According to [iScroll's document](http://iscrolljs.com/#custom-events), the scroll event is available on iScroll probe edition only. You can import it by `import iScroll from "iscroll/build/iscroll-probe"`.

**Comment by fanzihui** [comment]
我导入了这个 `import iScroll from "iscroll/build/iscroll-probe` ,但是发现只有使用 `pullDownToRefresh` 这个的时候才会出现 `onScroll` 事件,另外,在 `onScroll,onScrollEnd`等对应的函数中无法使用 `this.state` 或者设置 `this.setState()` 时会报错

**Comment by swenyang** [comment]
You should also pass `options` props with `{probeType: 2}` (or `3`, but not `1`), because iScroll's default probeType is `1` and the scroll event is fired only when the scroller is not busy doing its stuff. As for calling `this.setState()` issue, you should bind your event handler with `this`, such as `onScroll={this.onScrolling.bind(this)}`

**Comment by fanzihui** [comment]
Thank you
